name: lsv
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#01478d'
    - '#f14723'
    - '#01d0d6'
    - '#000000'
  brandStrength: 0.625
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0
purpose: []
